version: '3.8'
services:
  net-application:
    container_name: net-application
    image: 13072347/docker-app
    restart: always
    networks:
      - mynetwork

  grafana:
    container_name: grafana-test
    image: grafana/grafana:latest
    volumes:
      - ./grafana/:/var/lib/grafana/
    networks:
      - mynetwork

  prometheus:
    container_name: prometheus-test
    image: prom/prometheus:latest
    volumes:
     - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    networks: 
      - mynetwork

  jenkins:
    container_name: jenkins-test
    image: jenkins/jenkins:lts
    privileged: true
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - ./jenkins/jenkins_home/:/var/jenkins_home/
    networks:
      - mynetwork

  nginx:
    container_name: ingress-test
    image: nginx:latest
    restart: always
    ports:
      - 80:80
    networks:
      - mynetwork
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf


  ## for this container (sonarqube), require execute this command on host machine:
    ## sudo sysctl -w vm.max_map_count=262144
  sonarqube:
    container_name: sonarqube-test
    image: sonarqube:8-community
    depends_on:
      - postgres-db
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://postgres-db/sonarqube
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
      - sonarqube_temp:/opt/sonarqube/temp
    networks: 
      - mynetwork

  postgres-db:
    container_name: postgres-test
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: adminnn
      POSTGRES_PASSWORD: admin
    volumes: 
      - /var/lib/postgresql/data:/var/lib/postgresql/data
    networks: 
      - mynetwork

  adminer:
    container_name: adminer-test
    image: adminer
    restart: always
    environment: 
      ADMINER_DESIGN: galkaev
    networks: 
      - mynetwork

networks:
  mynetwork:
    driver: bridge

volumes:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:
  sonarqube_temp:
